[package]
name = "tarssh"
version = "0.1.0"
authors = ["Thomas Hurst <tom@hur.st>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
rand = "0.6.5"
tokio = "0.1.18"
env_logger = "0.6.1"
log = "0.4.6"
exitcode = "1.1.2"
