[package]
name = "tarssh"
version = "0.3.0"
description = "A simple SSH tarpit server"
authors = ["Thomas Hurst <tom@hur.st>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/Freaky/tarssh"
documentation  ="https://docs.rs/tarssh"
keywords = ["ssh", "tarpit", "security", "server"]
readme = "README.md"

[features]
default = ["sandbox", "drop_privs"]
sandbox = ["rusty-sandbox"]
drop_privs = ["privdrop"]

[dependencies]
env_logger = "0.6.1"
exitcode = "1.1.2"
futures-util-preview = "0.3.0-alpha.17"
log = "0.4.6"
structopt = "0.2.15"
tokio = { git = "https://github.com/tokio-rs/tokio" }
tokio-io = { git = "https://github.com/tokio-rs/tokio" }
tokio-signal = { git = "https://github.com/tokio-rs/tokio" }

[target."cfg(unix)".dependencies]
rusty-sandbox = { version = "0.2", optional = true }
privdrop = { version = "0.3.1", optional = true }
