[package]
name = "tarssh"
version = "0.1.0"
authors = ["Thomas Hurst <tom@hur.st>"]
edition = "2018"

[features]
default = ["sandbox", "drop_privs"]
sandbox = ["rusty-sandbox"]
drop_privs = ["privdrop", "nix"]

[dependencies]
futures = "0.1.25"
tokio = "0.1.18"
env_logger = "0.6.1"
log = "0.4.6"
structopt = "0.2.15"

[target."cfg(unix)".dependencies]
rusty-sandbox = { git = "https://github.com/Freaky/rusty-sandbox", branch = "sandbox-this-process-result", optional = true }
privdrop = { version = "0.2.2", optional = true }
nix = { version = "0.13.0", optional = true }
